---
title: "Strength of Evidence"
date: "`r format(Sys.time(), '%d %B, %Y (%H:%M)')`"
output:
  workflowr::wflow_html:
    font: Source Sans Pro
    theme: cosmo
    anchor_sections: TRUE 
    toc: yes
    toc_depth: 3
    toc_float: 
      collapsed: FALSE
      smooth_scroll: yes
    linkcolor: black
  latex_engine: xelatex
  pdf_document:
    toc: yes
    toc_depth: '4'
workflowr:
  suppress_report: TRUE
editor_options:
  chunk_output_type: console     
---

#### 

```{=html}
<style type="text/css">
  body{
  font-size: 9.5pt;
  font-family: Source Sans Pro;
}

.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
  color: #090909;
  background-color: #0909093d;
}

.lightable-classic.lightable-hover tbody tr:hover {
    background-color: #c5d4e4;
}
.btn-xs, .btn-group-xs>.btn { 
display: none; 
}

.btn-default {
display: none !important; 
}

@font-face {
    font-family: "GRADE-quality";
    src: url();
    src: url('https://gradepro.org/fonts/GRADE-quality.eot');
    src: url('https://gradepro.org/fonts/GRADE-quality.eot?#iefix')
        format('embedded-opentype'),
      url('https://gradepro.org/fonts/GRADE-quality.woff') format('woff'),
      url('https://gradepro.org/fonts/GRADE-quality.ttf') format('truetype'),
      url('https://gradepro.org/fonts/GRADE-quality.svg#GRADE-quality')
        format('svg');
    font-weight: normal;
    font-style: normal;
  }

.quality-sign {
      font-family: 'GRADE-quality', Cambria, Helvetica, Arial;
      font-size: 10px;
      vertical-align: text-top;
    }

span { font-size: 3em;}

span b { font-size: 60%; font-weight: normal }


</style>
```

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, options(knitr.kable.NA = '', dev = 'svg'), knitr.graphics.error = FALSE,
                      warning = FALSE, message = FALSE)
library(kableExtra)
library(janitor)
library(countrycode)
library(Cairo)
library(tidyverse)
library(naniar)
library(formattable)

# soe.dat <- readxl::read_xlsx("data/ProteinSOE_013121.xlsx", range = "A5:Q21", sheet = "data") %>% 
#   clean_names()
# 
# soe_summary <- soe.dat %>% 
#   select(compare, outcome, grade, uspstf_ahrq, acc_aha, importance) %>% 
#   mutate(grade = case_when(
#     grade == "Low" ~ '⨁⨁<span style="font-size: 11px; margin: 2px 0px 0px 0px; position: absolute;" >◯◯</span>',
#     grade == "Very Low" ~ '<span style="font-size: 12px; margin: 0px 0px 0px -11px; position: absolute;" >⨁</span><span style="font-size: 11px; margin: 2px 0px 0px 0px; position: absolute;" >◯◯◯</span>'))
#     #grade == "Very Low" ~ '⨁<span style="font-size: 11px; margin: 2px 0px 0px 0px; position: absolute;" >◯◯◯</span>'))
# 
# domain_summary <- soe.dat %>% 
#   select(compare, outcome, design_n_pts, rob, consistency, directness, precision, other)

opt_font <-  c("Source Sans Pro")
opt_boot <- c("striped", "hover", "condensed")

tab_inc <- function() {
  table_n <- table_n + 1
  table_n}

fig_inc <- function() {
  figure_n <- figure_n + 1
  figure_n}

table_n <- 1
figure_n <- 1

pack_sub <- function(kable_input, name, a, b) {
  pack_rows(kable_input, name,
            start_row = a, end_row = b,
            label_row_css = "border-bottom: 0px solid;", color = "black", background = "white", bold = FALSE
  )
}

pack_top <- function(kable_input, name, a, b) {
  pack_rows(kable_input, name,
            start_row = a, end_row = b,
            label_row_css = "border-top: 1px solid;", color = "black", background = "#EBEBEB"
  )
}

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}
```

# Carbohydrate Drinks

<br>

## Ratings

<br>

<font size = 4> Table `r table_n`. Strength of evidence in studies comparing carbohydrate drinks with fasting in adults.  </font>

```{r chofasting, include = TRUE}
# soe_summary$grade_graphic <- cell_spec(soe_summary$grade_graphic, font_size = 4)

cho_soe.dat <- readxl::read_xlsx("data/SOE_CHO_021821.xlsx", range = "A1:AA19", sheet = "data_transpose") %>% 
  clean_names() %>% 
   mutate(
    n = paste0(n, outcome),
    # outcome = tools::toTitleCase(outcome),
    out_import = case_when(
      out_import == "Limited" ~ "Limited Importance",
      out_import == "Important" ~ "Important Not Critical",
      out_import == "Critical" ~ "Critical"))

cho_soe_summary <- cho_soe.dat %>%
  select(n, comparison, outcome, grade, uspstf, acc, out_import, result_summary, result_table) %>%
  mutate(
    grade = case_when(
    # grade == "very low" ~ "⨁", grade == "low" ~ "⨁⨁", grade == "moderate" ~ "⨁⨁⨁", grade == "high" ~ "⨁⨁⨁")
      grade == "very low" ~ '<span><span class="quality-sign">⨁</span><span class="quality-sign">◯</span><span class="quality-sign">◯</span><span class="quality-sign">◯</span>',
      grade == "low" ~ '<span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">◯</span><span class="quality-sign">◯</span>',
      grade == "moderate" ~ '<span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">◯</span>',
	  grade == "high" ~ '<span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span><span class="quality-sign">⨁</span>',  # )%>% 
      TRUE ~ grade)) %>%
  # table links
  mutate(
    uspstf = firstup(uspstf),
    result_table = ifelse(n == "1Hunger", "[Table 3](cho_010420.html#Hunger) <br>  [Figure 1](cho_010420.html#fig1)", result_table),
    result_table = ifelse(grepl("2Hung", n), "[Table 4](cho_010420.html#hunger_ratings) <br> [Figures 2 & 3](cho_010420.html#fig2)", result_table),
      result_table = ifelse(grepl("3Hunger", n), "[Table 4](cho_010420.html#hunger_ratings)", result_table),
    result_table = ifelse(n == "4Thirst", "[Table 5](cho_010420.html#Thirst) <br> [Figure 4](cho_010420.html#fig4)", result_table),
    result_table = ifelse(n == "5Nausea", "[Table 6](cho_010420.html#Nausea) <br> [Figure 5](cho_010420.html#fig5)", result_table),
    result_table = ifelse(grepl("6Discom", n), "[Table 7](cho_010420.html#Discomfort)", result_table),
    result_table = ifelse(grepl("7Satisf", n), "[Table 8](cho_010420.html#Patient_Satisfaction)", result_table),
    result_table = ifelse(grepl("8Aspir", n), "[Table 9](cho_010420.html#__Reported) <br> [Table 10](cho_010420.html#aspirate2)", result_table),
    result_table = ifelse(grepl("9Regurg", n), "[Table 11](cho_010420.html#Regurgitation)", result_table),
    result_table = ifelse(grepl("10Regurg", n), "[Table 11](cho_010420.html#Regurgitation)", result_table),
    result_table = ifelse(grepl("11Vomit", n), "[Table 12](cho_010420.html#Vomiting) <br> [Figure 7](cho_010420.html#fig7)", result_table),
    result_table = ifelse(grepl("12Compl", n), "[Table 13](cho_010420.html#Complications) <br> [Table 14](cho_010420.html#tab14) <br> [Figure 9](cho_010420.html#__Pooled_(adult_RCTs))", result_table),
    result_table = ifelse(grepl("13Resi", n), "[Table 15](cho_010420.html#Residual_Gastric_Volume) <br> [Figure 11](cho_010420.html#__Pooled_(adult_RCTs)23)", result_table)
    #result_table = ifelse(outcome == "Hunger (rating)", "[Table 4](cho_010420.html#hunger_ratings)", result_table)
    )

cho_soe_summary %>% 
  filter(comparison == "CHO_fasting") %>% 
  select(!c(comparison, n)) %>% 
    kbl(booktabs = T, align = c("llcclll"), escape = FALSE,
    col.names = c("Outcome", "\\ GRADE", "USPSTF/AHRQ", "ACC/AHA", "Importance", "&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; Summary", "Result Detail")) %>% 
  row_spec(0, bold = TRUE) %>% 
  # add_header_above(c(" " = 4, "LI" = 1, " " = 2), line = FALSE, angle = -45, font_size = 3) %>% 
  add_header_above(c(" " = 1, "Strength of Evidence" = 3, " " = 1, " " = 2), line = FALSE, bold = TRUE) %>%
  kable_styling(bootstrap_options = opt_boot, position = "left") %>% 
  kable_classic(full_width = TRUE, html_font = opt_font, position = "left", "hover") %>%
  column_spec(1, width = "12em") %>%  
  column_spec(c(2:4), width = "6em") %>% 
  column_spec(5, width = "7em") %>% 
  column_spec(6, width = "26em") %>% 
  column_spec(7, width = "9em") %>% 
  # pack_top(., "Patient Reported Outcomes", 1, 2) %>%
  footnote(general = "RGV: residual gastric volume; NRSI: nonrandomized studies of intervensions; SMD: standardized mean difference; PI: prediction interval; C-LD: Randomized or nonrandomized observational or registry studies with limitations of design or execution. Meta-analyses of such studies. Physiological or mechanistic studies in human subjects.",
           # alphabet = c("At time of endocoscopy = 0","'Did you feel hunger during the fasting period?'"),
           general_title = "",  
           footnote_as_chunk = FALSE)

table_n <- tab_inc()

```

<br>

## GRADE Domains

<br>

<font size = 4> Table `r table_n`. Domains for strength of evidence ratings in studies comparing carbohydrate drinks with fasting in adults. </font>

<br>

```{r chofastingDomain, include = TRUE, eval = TRUE}
domain_summary <- cho_soe.dat %>% 
  select(n, comparison, outcome, design, n_studies, n_pts, rob, consist, direct, prec, other, summary, ends_with("foot")) %>% 
  mutate(design = toupper(design)) %>% 
  filter(comparison == "CHO_fasting")

# add footnotes
foot_list <- domain_summary %>% 
  select(comparison, outcome, ends_with("_foot"))

domain_summary <- domain_summary %>% 
  mutate(
    consist = ifelse(grepl("1Hung", n), paste0(consist, "^1a^"),   consist),
    prec =    ifelse(grepl("1Hung", n), paste0(prec,    "^1b^"),   prec),
    consist = ifelse(grepl("2Hung", n), paste0(consist, "^2a2b^"), consist),
    consist = ifelse(grepl("3Hung", n), paste0(consist, "^3a^"),   consist),
    consist = ifelse(grepl("4Thir", n), paste0(consist, "^4a^"),   consist),
    prec =    ifelse(grepl("4Thir", n), paste0(prec,    "^4b^"),   prec),
    consist = ifelse(grepl("5Naus", n), paste0(consist, "^5a^"),   consist),
    consist = ifelse(grepl("6Disc", n), paste0(consist, "^6a^"),   consist),
    prec =    ifelse(grepl("6Disc", n), paste0(prec,    "^6b^"),   prec),
    consist = ifelse(grepl("7Sati", n), paste0(consist, "^7a^"),   consist),
    prec =    ifelse(grepl("7Sati", n), paste0(prec,    "^7b^"),   prec),    
    consist = ifelse(grepl("10Vom", n), paste0(consist, "^8a^"),   consist),
    rob =     ifelse(grepl("9Regu", n), paste0(rob,     "^9a^"),   rob),
    consist = ifelse(grepl("9Regu", n), paste0(consist, "^9b^"),   consist),
    prec =    ifelse(grepl("9Regu", n), paste0(prec,    "^9c^"),   prec),    
    consist = ifelse(grepl("10Reg", n), paste0(consist, "^10a^"),  consist),
    prec =    ifelse(grepl("10Reg", n), paste0(prec,    "^10b^"),  prec),   
    consist = ifelse(grepl("11Vom", n), paste0(consist, "^11a^"),  consist),
    consist = ifelse(grepl("12Com", n), paste0(consist, "^12a^"),  consist),
    direct  = ifelse(grepl("13Res", n), paste0(direct,  "^13a^"),  direct)
    )

footnotes <- c(
  "1a Considerable heterogeneity (*I^2^* = 90%).",
  "1b Wide confidence intervals consistent with either carbohydrate or fasting being accompanied by a lower risk of hunger.",
  "2a Considerable heterogeneity (*I^2^* = 90%) yielding a prediction interval consistent with lower hunger ratings after  either CHO or fasting.", 
  "2b Measurements taken at different times.",
  "3a Studies reported inconsistent results.",
  "4a Considerable heterogeneity (*I^2^* = 86%).",
  "4b Wide confidence intervals consistent with either CHO or fasting being accompanied by a lower risk of thirst.",
  "5a Measurement taken at different times; considerable heterogeneity (*I^2^* = 75%).",
  "6a Single study, cannot assess consistency.",
  "6b Wide confidence interval.",
  "7a Studies report inconsistent results and measurement taken at different times.",
  "7b Assuming both studies used a 10-point scale, the pooled estimate was  accompanied by considerable uncertainty — MD 1.00 (95% CI, -0.96 to 2.96).",
  "9a Unclear ascertainment accuracy or if Koeppe 2013 assessment exceedingly sensitive.",
  "9b A single RCT reported any regurgitation, consistency cannot be assessed.",
  "9c Single RCT (98 patients) with wide confidence interval.",
  "10a Single study, cannot assess consistency.",
  "10b 1 event, precision unclear.",
  "11a Measurements taken at different times and substantial heterogeneity (*I^2^* = 63%).",
  "12a Varied definitions of complication.",
  "13a Strength of relationship with aspiration unclear, but for comparative purposes may be considered direct.")
  # "Wide confidence interval(s) indicate uncertainty concerning results.",
  # "Studies report inconsistent results and measurement taken at different times."

domain_summary %>% 
  filter(comparison == "CHO_fasting") %>% 
  mutate(n_s = paste0(n_studies, " (", n_pts, ")")) %>% 
  select(outcome, design, n_s, rob, consist, direct, prec, other) %>% 
    kbl(booktabs = T, align = c("lcllllll"), escape = FALSE, padding = 10, 
    col.names = c("Outcome", "Design", "N (pts)", "Bias", "Consistency", "Directness", "Precision", "Other")) %>% 
  row_spec(0, bold = TRUE) %>% 
  add_header_above(c(" " = 1, "Studies" = 2, "Domains" = 5), line = TRUE, bold = TRUE) %>%
  kable_styling(bootstrap_options = opt_boot, position = "left") %>% 
  kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>%
  column_spec(1, width = "13em") %>%  
  column_spec(2, width = "4em") %>% 
  column_spec(3, width = "10em") %>% 
  column_spec(4:8, width = "8em") %>% 
  footnote(general = "RCT: randomized controlled trials; NRSI: nonrandomized studies of intervensions.",
           alphabet = footnotes,
           general_title = "",  
           footnote_as_chunk = FALSE)

table_n <- tab_inc()
```

<br>

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<br>

<!-- # Carbohydrate/Protein Evidence -->

<!-- <br> -->

<!-- <font size = 4> Table `r table_n`. Strength of evidence in studies comparing protein/carbohydrate drinks versus fasting in adults.   </font> -->

<!-- ```{r protVfasting, include = FALSE, eval = FALSE} -->
<!-- #soe_summary$grade_graphic <- cell_spec(soe_summary$grade_graphic, font_size = 4) -->

<!-- soe_summary %>%  -->
<!--   filter(compare == "prot_fasting", outcome == "RGV") %>%  -->
<!--   group_by(outcome) %>%  -->
<!--   slice(1) %>%  -->
<!--   ungroup() %>%  -->
<!--   select(!compare) %>%  -->
<!--     kbl(booktabs = T, align = c("lcccc"), escape = FALSE, -->
<!--     col.names = c("Outcome", "\\ \\ \\ GRADE", "USPSTF/AHRQ", "ACC/AHA", "Importance")) %>%  -->
<!--   add_header_above(c(" " = 1, "Strength of Evidence" = 3, " " = 1), line = TRUE) %>% -->
<!--   kable_styling(bootstrap_options = opt_boot, position = "left") %>%  -->
<!--   kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>% -->
<!--   column_spec(1, width = "4em") %>%   -->
<!--   column_spec(2, width = "4em") %>%  -->
<!--   column_spec(3, width = "4em") %>%  -->
<!--   column_spec(4, width = "4em") %>%  -->
<!--   column_spec(5, width = "3em") %>%  -->
<!--   footnote(general = "RGV: residual gastric volume; CHO: carbohydrate; C-LD: Randomized or nonrandomized observational or registry studies with limitations of design or execution. Meta-analyses of such studies. Physiological or mechanistic studies in human subjects.", -->
<!--            # alphabet = c("At time of endocoscopy = 0","'Did you feel hunger during the fasting period?'"), -->
<!--            general_title = "",   -->
<!--            footnote_as_chunk = FALSE) -->

<!-- table_n <- tab_inc() -->
<!-- ``` -->

<!-- <font size = 4> Table `r table_n`. Domains for strength of evidence ratings in studies comparing protein/carbohydrate drinks versus fasting in adults. </font> -->

<!-- ```{r protVfastingDomain, include = FALSE, eval = FALSE} -->
<!-- #soe_summary$grade_graphic <- cell_spec(soe_summary$grade_graphic, font_size = 4) -->

<!-- soe.dat <- readxl::read_xlsx("data/ProteinSOE_013121.xlsx", range = "A5:Q21", sheet = "data") %>% -->
<!--   clean_names() -->

<!-- soe_summary <- soe.dat %>% -->
<!--   select(compare, outcome, grade, uspstf_ahrq, acc_aha, importance) %>% -->
<!--   mutate(grade = case_when( -->
<!--     grade == "Low" ~ '⨁⨁<span style="font-size: 11px; margin: 2px 0px 0px 0px; position: absolute;" >◯◯</span>', -->
<!--     grade == "Very Low" ~ '<span style="font-size: 12px; margin: 0px 0px 0px -11px; position: absolute;" >⨁</span><span style="font-size: 11px; margin: 2px 0px 0px 0px; position: absolute;" >◯◯◯</span>')) -->
<!--     #grade == "Very Low" ~ '⨁<span style="font-size: 11px; margin: 2px 0px 0px 0px; position: absolute;" >◯◯◯</span>')) -->

<!-- domain_summary <- soe.dat %>% -->
<!--   select(compare, outcome, design_n_pts, rob, consistency, directness, precision, other) -->

<!-- domain_summary %>%  -->
<!--   filter(compare == "prot_fasting", outcome == "RGV") %>%  -->
<!--   group_by(outcome) %>%  -->
<!--   slice(1) %>%  -->
<!--   ungroup() %>%  -->
<!--   select(!compare) %>%  -->
<!--     kbl(booktabs = T, align = c("lcccccc"), escape = FALSE, -->
<!--     col.names = c("Outcome", "Design: N (pts)", "Bias", "Consistency", "Directness", "Precision", "Other")) %>%  -->
<!--   add_header_above(c(" " = 1, "Studies", "Domains" = 5), line = TRUE) %>% -->
<!--   kable_styling(bootstrap_options = opt_boot, position = "left") %>%  -->
<!--   kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>% -->
<!--   column_spec(1, width = "4em") %>%   -->
<!--   column_spec(2, width = "12em") %>%  -->
<!--   column_spec(3:7, width = "8em") %>%  -->
<!--   # column_spec(4, width = "4em") %>%  -->
<!--   # column_spec(5, width = "3em") %>%  -->
<!--   footnote(general = "RGV: residual gastric volume; RCT: randomized controlled trials.", -->
<!--            alphabet = c("Strength of causal relationship with aspiration unclear.", -->
<!--                         "Small sample sizes."), -->
<!--                         # "High heterogeneity"), -->
<!--            general_title = "",   -->
<!--            footnote_as_chunk = FALSE) -->

<!-- table_n <- tab_inc() -->
<!-- ``` -->



<!-- see [Table 3](cho_010420.html#Hunger) -->

<!-- see [RGV result](https://mdgrant.github.io/Fasting/protein_combined_120820.html#Residual_Gastric_Volume,_pH) -->



 
